<?php

use Illuminate\Database\Seeder;

class PegawaiTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pegawai')->delete();
        
        \DB::table('pegawai')->insert(array (
            0 => 
            array (
                'id' => 1,
                'nip' => '196211211989091001',
                'nama' => 'Dr. Ir. FERRY SOFWAN ARIF, M.Si',
                'golongan' => 'IV/d',
                'pangkat' => 'Pembina Utama Madya',
                'jabatan' => 'Inspektur',
                'eselon' => 'II',
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'nip' => '196507171992091001',
                'nama' => 'Drs. SUBANDRIO ILHAM BASUKI',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Sekretaris',
                'eselon' => 'III',
                'created_at' => '2020-02-28 01:31:41',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'nip' => '196311261997031002',
                'nama' => 'DEDI SAPUTRA, S.H., M.AP',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Inspektur Pembantu Bidang Pemerintahan dan Kesejahteraan Masyarakat',
                'eselon' => 'III',
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'nip' => '197005261995032001',
                'nama' => 'ATI HOEROWATI, S.H., M.Si., CFrA',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Inspektur Pembantu Bidang Administrasi',
                'eselon' => 'III',
                'created_at' => '2020-02-28 01:31:41',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'nip' => '196603151988031001',
                'nama' => 'HIDAJAT SETIAPUTRA, Ak., M.M.',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Inspektur Pembantu Bidang Khusus',
                'eselon' => 'III',
                'created_at' => '2020-02-28 01:31:41',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'nip' => '196203071989031003',
                'nama' => 'TATA TARYONO, S.Sos., M.Si.',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Inspektur Pembantu Bidang Perekonomian dan Pembangunan',
                'eselon' => 'III',
                'created_at' => '2020-02-28 01:31:41',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'nip' => '197805052005011016',
                'nama' => 'GANDJAR YUDNIARSA, S.T., M.T.',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Kepala Sub Bagian Perencanaan dan Pelaporan',
                'eselon' => 'IV',
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'nip' => '197809022002122002',
                'nama' => 'TITI MARTINI, S.TP., M.M.',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Kepala Sub Bagian Keuangan dan Aset',
                'eselon' => 'IV',
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'nip' => '198008272010011011',
                'nama' => 'AGUS MULYADI SULAIMAN, S.E.',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Analis Perencanaan, Evaluasi dan Pelaporan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'nip' => '198606092010011004',
                'nama' => 'GHILANG GUMILAR GUNAWAN, S.E., M.M.',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Analis Perencanaan, Evaluasi dan Pelaporan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'nip' => '196412011989081001',
                'nama' => 'TATANG KOSWARA',
                'golongan' => 'III/b',
                'pangkat' => 'Penata Muda Tk.I',
                'jabatan' => 'Pengelola Evaluasi Tindak Lanjut Laporan Hasil Pemeriksaan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'nip' => '196507151991031010',
                'nama' => 'MOHAMAD ASEP WIBIKSANA',
                'golongan' => 'III/b',
                'pangkat' => 'Penata Muda Tk.I',
                'jabatan' => 'Pengelola Evaluasi Tindak Lanjut Laporan Hasil Pemeriksaan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:28:39',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'nip' => '197310311996032001',
                'nama' => 'LIA RUSLIAWATI, A.Md',
                'golongan' => 'III/b',
                'pangkat' => 'Penata Muda Tk.I',
                'jabatan' => 'Analis Laporan Hasil Pengawasan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:28:39',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'nip' => '197701072010011008',
                'nama' => 'THAUFIQ RANGGAJAYA, S.T.',
                'golongan' => 'III/b',
                'pangkat' => 'Penata Muda Tk.I',
                'jabatan' => 'Perencana Pertama',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'nip' => '197408112007011009',
                'nama' => 'AGUS DAMHUDI, S.Sos',
                'golongan' => 'III/a',
                'pangkat' => 'Penata Muda',
                'jabatan' => 'Pengolah Data Perencanaan dan Penganggaran',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'nip' => '198407172010012012',
                'nama' => 'SUCI MEIDINA, S.E.',
                'golongan' => 'III/a',
                'pangkat' => 'Penata Muda',
                'jabatan' => 'Analis Laporan Hasil Pengawasan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'nip' => '196809161990081001',
                'nama' => 'AMIN',
                'golongan' => 'II/d',
                'pangkat' => 'Pengatur Tk.I',
                'jabatan' => 'Pengadministrasi Perencanaan dan Program',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:30:01',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'nip' => '197706102009011002',
                'nama' => 'ASEP JUHANA',
                'golongan' => 'II/c',
                'pangkat' => 'Pengatur',
                'jabatan' => 'Pengelola Evaluasi Tindak Lanjut Laporan Hasil Pemeriksaan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'nip' => '197306182014101002',
                'nama' => 'DUDE ACHMAD SYAEHU',
                'golongan' => 'II/b',
                'pangkat' => 'Pengatur Muda Tk.I',
                'jabatan' => 'Pengadministrasi Perencanaan dan Program',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:29:35',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'nip' => '196705061993031007',
                'nama' => 'DAYAT SUDRAJAT, S.E.',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Pengelola Keuangan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'nip' => '197204062008012008',
                'nama' => 'ONEH ROHANAH, S.E.',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Pengelola Keuangan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'nip' => '197604232009011002',
                'nama' => 'HASAN ISHAK, S.E.',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Verifikatur',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'nip' => '198512282011012001',
                'nama' => 'WIKATININGSIH, S.E., M.I.P',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Analis Laporan Keuangan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'nip' => '197901272010012001',
                'nama' => 'TITI MUGIATI, S.E.',
                'golongan' => 'III/b',
                'pangkat' => 'Penata Muda Tk.I',
                'jabatan' => 'Verifikatur',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'nip' => '197106022007012005',
                'nama' => 'SONI SUNINGSIH, S.I.Kom.',
                'golongan' => 'III/a',
                'pangkat' => 'Penata Muda',
                'jabatan' => 'Pengelola Keuangan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'nip' => '197609032008012007',
                'nama' => 'RIKA SUPIANTI, S.E.',
                'golongan' => 'III/a',
                'pangkat' => 'Penata Muda',
                'jabatan' => 'Pengelola Keuangan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'nip' => '198710182011012002',
                'nama' => 'EKA BIDA BIDANI, A.Md',
                'golongan' => 'III/a',
                'pangkat' => 'Penata Muda',
                'jabatan' => 'Bendahara',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'nip' => '197103032008011003',
                'nama' => 'DEDE MIHARNA',
                'golongan' => 'II/b',
                'pangkat' => 'Pengatur Muda Tk.I',
                'jabatan' => 'Pengadministrasi Keuangan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'nip' => '197501022009011002',
                'nama' => 'AEP NURDIN',
                'golongan' => 'II/b',
                'pangkat' => 'Pengatur Muda Tk.I',
                'jabatan' => 'Pengelola Gaji',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'nip' => '197106142007011013',
                'nama' => 'RADI',
                'golongan' => 'II/b',
                'pangkat' => 'Pengatur Muda Tk.I',
                'jabatan' => 'Pengadministrasi Keuangan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'nip' => '198509022014121001',
                'nama' => 'HERU EKA NURHASYAN NURDIN',
                'golongan' => 'II/b',
                'pangkat' => 'Pengatur Muda Tk.I',
                'jabatan' => 'Pengadministrasi Keuangan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:29:35',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'nip' => '196312121987031010',
                'nama' => 'Drs. SUBADRA',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Pengadministrasi Umum',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'nip' => '196906101998031006',
                'nama' => 'BUDI KRISTIADI MISBACH, S.Kom',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Pengelola Barang Milik Negara',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'nip' => '197912152010012006',
                'nama' => 'HENY YUNIAR, S.Sos',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Pengelola Barang Milik Negara',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'nip' => '198607112010012002',
                'nama' => 'YOSI HERLIA SAFITRI, S.E.',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Pengelola Kepegawaian',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'nip' => '197910022011012001',
                'nama' => 'HENNY KUSUMAWARDANI, S.Sos',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Analis Sumber Daya Manusia Aparatur',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'nip' => '196402271986031009',
                'nama' => 'MOCHAMAD GANDJAR',
                'golongan' => 'III/b',
                'pangkat' => 'Penata Muda Tk.I',
                'jabatan' => 'Pengadministrasi Umum',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'nip' => '199209212014062002',
                'nama' => 'DEWI SEPTIANTI HADI, S.STP',
                'golongan' => 'III/b',
                'pangkat' => 'Penata Muda Tk.I',
                'jabatan' => 'Pengelola Kepegawaian',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:28:39',
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'nip' => '198306302015032001',
                'nama' => 'KAMIA ACHYUNIASIH KUNRAT, S.Sos',
                'golongan' => 'III/b',
                'pangkat' => 'Penata Muda Tk.I',
                'jabatan' => 'Analis Sumber Daya Manusia Aparatur',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'nip' => '196504022007011005',
                'nama' => 'DADAN',
                'golongan' => 'II/d',
                'pangkat' => 'Pengatur Tk.I',
                'jabatan' => 'Pengadministrasi Umum',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:30:01',
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'nip' => '197108152008011001',
                'nama' => 'DAHYAN',
                'golongan' => 'II/c',
                'pangkat' => 'Pengatur',
                'jabatan' => 'Pengemudi',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'nip' => '196208242008011001',
                'nama' => 'RUSLI',
                'golongan' => 'II/b',
                'pangkat' => 'Pengatur Muda Tk.I',
                'jabatan' => 'Pengemudi',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:29:35',
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'nip' => '197104182008011003',
                'nama' => 'WAWAN SETIAWAN',
                'golongan' => 'II/b',
                'pangkat' => 'Pengatur Muda Tk.I',
                'jabatan' => 'Pengadministrasi Umum',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'nip' => '197805082014101001',
                'nama' => 'AHMAD',
                'golongan' => 'II/b',
                'pangkat' => 'Pengatur Muda Tk.I',
                'jabatan' => 'Pengadministrasi Umum',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'nip' => '198110212014102001',
                'nama' => 'IRA INDRIANI',
                'golongan' => 'II/b',
                'pangkat' => 'Pengatur Muda Tk.I',
                'jabatan' => 'Pengadministrasi Umum',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'nip' => '198208032014101001',
                'nama' => 'AGUS SURYANA',
                'golongan' => 'II/b',
                'pangkat' => 'Pengatur Muda Tk.I',
            'jabatan' => 'Pengelola Barang Milik Negara (Penyimpan Barang)',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'nip' => '198205052014121005',
                'nama' => 'SUPRIADI',
                'golongan' => 'II/b',
                'pangkat' => 'Pengatur Muda Tk.I',
                'jabatan' => 'Pengadministrasi Umum',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:29:35',
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'nip' => '196504071994031010',
                'nama' => 'SUNARYA',
                'golongan' => 'II/a',
                'pangkat' => 'Pengatur Muda',
                'jabatan' => 'Pengadministrasi Umum',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'nip' => '197502022014121001',
                'nama' => 'YUDI',
                'golongan' => 'I/d',
                'pangkat' => 'Juru Tk.I',
                'jabatan' => 'Pengadministrasi Umum',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'nip' => '198006162014101001',
                'nama' => 'AHMAD SUMARNA',
                'golongan' => 'I/d',
                'pangkat' => 'Juru Tk.I',
                'jabatan' => 'Pengadministrasi Umum',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'nip' => '196608052014101001',
                'nama' => 'RUSMADI',
                'golongan' => 'I/b',
                'pangkat' => 'Juru Muda Tk.I',
                'jabatan' => 'Pengemudi',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:27:33',
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'nip' => '198204272014101001',
                'nama' => 'DIDIN',
                'golongan' => 'I/b',
                'pangkat' => 'Juru Muda Tk.I',
                'jabatan' => 'Pengemudi',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'nip' => '196203211993021001',
                'nama' => 'Ir.RUDY',
                'golongan' => 'IV/c',
                'pangkat' => 'Pembina Utama Muda',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'nip' => '196009151981031007',
                'nama' => 'Drs. KARYONO, M.Si.',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'nip' => '196612291990021001',
                'nama' => 'ADE IMANSAH, A.Ks., M.Si',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Pemeriksa Transaksi Keuangan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:31:41',
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'nip' => '196112031982031010',
                'nama' => 'CUCU SUHADA, S.Sos, MM',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Auditor Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'nip' => '196002041983031014',
                'nama' => 'RADEN KUNDRAT, S.Sos',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Auditor Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'nip' => '196202081992021002',
                'nama' => 'DODY SOTANDI, S.H.',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'nip' => '196806051992031013',
                'nama' => 'TAUFIK ROCHMAN, S.Sos., MM',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Auditor Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'nip' => '196902091993031001',
                'nama' => 'MAILAN REPLITA, SE',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Auditor Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'nip' => '196801191997032005',
                'nama' => 'Ir. LENI LESTIATI',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'nip' => '196303011997031002',
                'nama' => 'DIDIN SUPRIABUDIN, SH',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Auditor Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'nip' => '197204031998031001',
                'nama' => 'AKHMAD MUKHLIS, S.E., M.Si.',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'nip' => '196608281993121001',
                'nama' => 'Drs. KUSNANDI',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'nip' => '196404101994031004',
                'nama' => 'ASEP WAHYU, S.Sos',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Auditor Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:29:12',
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'nip' => '197503131998031002',
                'nama' => 'ANDY WACHYU GUNAWAN, SIP',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Auditor Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'nip' => '197709072006041003',
                'nama' => 'TITO MAHESA SENJAYA, S.P., M.P.',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Auditor Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'nip' => '197003132006041001',
                'nama' => 'NANAS DARSANA, SE',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'nip' => '198108142006041007',
                'nama' => 'RYAN HIDAYAT, S.T., M.T',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Auditor Pertama',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'nip' => '197401142008012002',
                'nama' => 'DINI TRESNAWATI, ST',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'nip' => '198103032010012014',
                'nama' => 'DIAN INDRAYANI, SE',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Auditor Pertama',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'nip' => '198403212009012006',
                'nama' => 'IRMA RUSDINI, S.AB',
                'golongan' => 'III/b',
                'pangkat' => 'Penata Muda Tk.I',
                'jabatan' => 'Auditor Pertama',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'nip' => '198710212010011001',
                'nama' => 'RYAN SOFHIAN RUSDIANA, SE., Ak',
                'golongan' => 'III/b',
                'pangkat' => 'Penata Muda Tk.I',
                'jabatan' => 'Auditor Pelaksana Lanjutan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'nip' => '198812272010121002',
                'nama' => 'BAYU ADJIE PRATAMA, A.Md.',
                'golongan' => 'III/a',
                'pangkat' => 'Penata Muda',
                'jabatan' => 'Pemeriksa Transaksi Keuangan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'nip' => '196009161983031013',
                'nama' => 'Drs. IMAN HAMDANI, M.Si',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'nip' => '196205231985031006',
                'nama' => 'RADAN, S.Sos., M.Si',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Auditor Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'nip' => '197010211990061001',
                'nama' => 'Drs. TEDDY ZULKARNAEN, M.Si',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:31:41',
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'nip' => '197010071992031004',
                'nama' => 'ACHMAD ROBIANA, S.E., M.Si',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Auditor Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:28:14',
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'nip' => '196003261993012001',
                'nama' => 'TOETY ENDRAYATI, S.Sos., M.Si.',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Auditor Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:31:41',
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'nip' => '196611041990032003',
                'nama' => 'ELYNA S LAURA SIAHAAN, SKp, MH',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'nip' => '196802031996031002',
                'nama' => 'PERI WAHJUROHIM, SIP',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'nip' => '196203071998031002',
                'nama' => 'TEDDIE ADRIANSYAH, S.H.',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'nip' => '197610302006041002',
                'nama' => 'SANI AFDHALUDDIN, S.E., M.Si., Ak',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'nip' => '197611141999031001',
                'nama' => 'KARYANI, C.A., S.E., Ak., M.Si.',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Pemeriksa Transaksi Keuangan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'nip' => '197412282000031001',
                'nama' => 'YOSEF TAUFIK HIDAYAT, S.Kom., M.Kom',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'nip' => '197607262005011010',
                'nama' => 'YANYAN KRISTIANA, S.E.',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'nip' => '197903302005012008',
                'nama' => 'ARI INDRIANI, S.E., M.M.',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'nip' => '197512042008012001',
                'nama' => 'NUR\'AINI ILMI TANJUNG, S.E., M.Si',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:29:12',
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'nip' => '196712191993031004',
                'nama' => 'SAEFUL SISWANTARA, S.Sos',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Auditor Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'nip' => '196704152006041006',
                'nama' => 'ASEP SEMBADA, S.Sos',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'nip' => '198003022011012001',
                'nama' => 'EMMA MULYANI RACHMAN, SE., MAP',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Auditor Pertama',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'nip' => '198706172015021001',
                'nama' => 'REZA MARTHA PRADANA, S.E.',
                'golongan' => 'III/a',
                'pangkat' => 'Penata Muda',
                'jabatan' => 'Auditor Pertama',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'nip' => '196601111988031010',
                'nama' => 'Drs. TOTO SUARTO, M.Si',
                'golongan' => 'IV/c',
                'pangkat' => 'Pembina Utama Muda',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'nip' => '196312021986031001',
                'nama' => 'ACE, S.E., Ak.',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Auditor Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:28:14',
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'nip' => '196403201989031008',
                'nama' => 'TATAN SONTANI, S.E., M.Si',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Auditor Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'nip' => '197402141994021001',
                'nama' => 'HARY NURMAN, A.P.',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'nip' => '196508181996032001',
                'nama' => 'TRIYANA KUMALA, S.H., M.Si',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Auditor Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'nip' => '196405271997031003',
                'nama' => 'Ir. RADEN  HERIJANTO, M.Ak',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'nip' => '196706161989021001',
                'nama' => 'Drs. MOCH. IWAN SETIAWAN, M.Si',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'nip' => '196512281986031002',
                'nama' => 'YANI SUKMAWAN, S.E., Ak.',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'nip' => '196608011989031007',
                'nama' => 'TONNY EFFENDY, SH',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Auditor Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'nip' => '197007251993031003',
                'nama' => 'HERDIANTO, S.Sos',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'nip' => '197109161995031001',
                'nama' => 'DENI SUSANTO, S.Sos',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'nip' => '196902141996031001',
                'nama' => 'DJUMARTONO, Ak',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Auditor Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:29:12',
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'nip' => '196909122000121001',
                'nama' => 'GANDJAR PRAKOSA, S.E.',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:29:12',
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'nip' => '198506092008121001',
                'nama' => 'BOBBY DAHNI RESJA, S.E.',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Pemeriksa Transaksi Keuangan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:29:12',
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'nip' => '197208161996031002',
                'nama' => 'AGUS TEDI HERYADI, S.IP',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'nip' => '197505312008122001',
                'nama' => 'WIWIET HERTIARANI, S.E., M.AP',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Pemeriksa Transaksi Keuangan',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'nip' => '197007112008011002',
                'nama' => 'DENI KOMARA ALAMSYAH, S.Sos',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'nip' => '198703252010122002',
                'nama' => 'IIS SOLIHAT, SE., M.Ak., Ak., CA',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Auditor Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'nip' => '198702142011012005',
                'nama' => 'VALENTINE DIAN HERNISAPUTRI, S.E.',
                'golongan' => 'III/a',
                'pangkat' => 'Penata Muda',
                'jabatan' => 'Auditor Pertama',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'nip' => '196010271985031008',
                'nama' => 'Drs. BACHTIAR HARMANSJAH M, M.Pd.',
                'golongan' => 'IV/c',
                'pangkat' => 'Pembina Utama Muda',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'nip' => '196104081985031006',
                'nama' => 'KAHPI, SP',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Auditor Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'nip' => '196107011989091002',
                'nama' => 'Ir. TOTO HERMANTO, M.Si',
                'golongan' => 'IV/b',
                'pangkat' => 'Pembina Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'nip' => '197107251991012001',
                'nama' => 'EVY JULIAWATY, S.IP., M.Si',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'nip' => '196812131992031004',
                'nama' => 'MUHAMAD YUSUF, S.Sos., M.Si',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Auditor Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'nip' => '196202221997032001',
                'nama' => 'Dra. YAYU SITI RAHAYU',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Auditor Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'nip' => '197409242002122002',
                'nama' => 'BERIN BERLIANTY, S.H., M.Si',
                'golongan' => 'IV/a',
                'pangkat' => 'Pembina',
                'jabatan' => 'Pengawas Pemerintahan Madya',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'nip' => '196209171983031008',
                'nama' => 'DIDING ISKANDAR',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Auditor Penyelia',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:29:12',
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'nip' => '196409101986031018',
                'nama' => 'NANANG JUMARA, SE',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'nip' => '196808041996031002',
                'nama' => 'AGUS MIRAKUSUMAH, S.E.',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Auditor Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'nip' => '197710242006041006',
                'nama' => 'SYAIFUDDIN, SE',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Auditor Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:29:12',
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'nip' => '197705132006041006',
                'nama' => 'ANDRIS WIRAWAN, ST., MM',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Auditor Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:29:12',
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'nip' => '196910222006041001',
                'nama' => 'YAN HERYANA, S.E.',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'nip' => '197611252006042003',
                'nama' => 'VITYARTI SARI RAHAYU NINGSIH, S.Komp., M.Si',
                'golongan' => 'III/d',
                'pangkat' => 'Penata Tk.I',
                'jabatan' => 'Auditor Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:29:12',
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'nip' => '196510231988031007',
                'nama' => 'SUGENG, S.E.',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'nip' => '196908051993031005',
                'nama' => 'INDRA SUHANDA, S.Sos',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Pengawas Pemerintahan Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'nip' => '197002102007012007',
                'nama' => 'AAN ANDRIJANI, S.T., M.Si',
                'golongan' => 'III/c',
                'pangkat' => 'Penata',
                'jabatan' => 'Auditor Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'nip' => '198502162010011004',
                'nama' => 'FERY KUSUMAWARDANI, S.ST.Par., M.Si',
                'golongan' => 'III/b',
                'pangkat' => 'Penata Muda Tk.I',
                'jabatan' => 'Auditor Pertama',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:28:39',
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'nip' => '198503152010011006',
                'nama' => 'YOGI MARPIAN, S.IP., M.Si.',
                'golongan' => 'III/b',
                'pangkat' => 'Penata Muda Tk.I',
                'jabatan' => 'Auditor Pertama',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'nip' => '198010282010011007',
                'nama' => 'ARIF SUPRIATNA, SE., MM',
                'golongan' => 'III/b',
                'pangkat' => 'Penata Muda Tk.I',
                'jabatan' => 'Auditor Muda',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'nip' => '198505132011012004',
                'nama' => 'RINI ROSNAWATY, SE',
                'golongan' => 'III/a',
                'pangkat' => 'Penata Muda',
                'jabatan' => 'Auditor Pertama',
                'eselon' => NULL,
                'created_at' => '2020-02-28 01:22:16',
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}